sample_users = [
    {
        "id": 1,
        "username": "vdighe",
        "fullname": "Vaishali Dighe-Phanse",
        "email": "vaishphanse@gmail.com",
        "password": "xyz",
        "is_admin": true
    },    {
        "id": 2,
        "username": "ctphanse",
        "fullname": "CT Phan",
        "email": "ctphan@gmail.com",
        "password": "xyz",
        "is_admin": false
    }
]

sample_books = [{"book_id": "QGhkQ",
                 "olid": "OL22549594M",
                 "title": "The Hunger Games",
                 "subtitle": "",
                 "author": "Suzanne Collins",
                 "user_id": 1,
                 "requested_by": [2],
                 "lend_to": None},
                {"book_id": "bbd2j",
                 "olid": "OL7318410M",
                 "title": "KAFKA ON THE SHORE",
                 "subtitle": "",
                 "author": "Haruki Murakami",
                 "user_id": 1,
                 "requested_by": [],
                 "lend_to": None},
                {"book_id": "QGhkr",
                 "olid": "OL24842593M",
                 "title": "Ready Player One",
                 "subtitle": "",
                 "author": "Ernest Cline",
                 "user_id": 2,
                 "requested_by": [1, 3],
                 "lend_to": None},
                {"book_id": "bbd2K",
                 "olid": "OL24767475M",
                 "title": "Xenogenesis",
                 "subtitle": "",
                 "author": "Octavia E. Butler",
                 "user_id": 2,
                 "requested_by": [],
                 "lend_to": None},
                {"book_id": "4n7Vz",
                 "olid": "OL16159793M",
                 "title": "The Name of the Wind",
                 "subtitle": "",
                 "author": "Patrick Rothfuss",
                 "user_id": 3,
                 "requested_by": [1, 2],
                 "lend_to": None},
                {"book_id": "bad3K",
                 "olid": "OL7470646M",
                 "title": "Dune",
                 "subtitle": "",
                 "author": "Frank Herbert",
                 "user_id": 3,
                 "requested_by": [1],
                 "lend_to": None}]

